//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatrixTraceProject.Properties.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MatrixTraceProject.Properties.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not entered anything.
        /// </summary>
        internal static string EmptyString {
            get {
                return ResourceManager.GetString("EmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application &quot;Matrix Trace&quot; fill matrix with random numbers and find a matrix trace. Copyright 2022
        ///.
        /// </summary>
        internal static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers of colomns: .
        /// </summary>
        internal static string InputColumns {
            get {
                return ResourceManager.GetString("InputColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input matrix dimensions, at first number of rows: .
        /// </summary>
        internal static string InputRows {
            get {
                return ResourceManager.GetString("InputRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your&apos;s matrix:.
        /// </summary>
        internal static string MatrixPrint {
            get {
                return ResourceManager.GetString("MatrixPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Your&apos;s matrix in spiral order:
        ///{0}.
        /// </summary>
        internal static string MatrixPrintInSpiralOrder {
            get {
                return ResourceManager.GetString("MatrixPrintInSpiralOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Your&apos;s matrix trace: {0}.
        /// </summary>
        internal static string MatrixTrace {
            get {
                return ResourceManager.GetString("MatrixTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You input wrong dimension. Try again..
        /// </summary>
        internal static string WrongDimension {
            get {
                return ResourceManager.GetString("WrongDimension", resourceCulture);
            }
        }
    }
}
